GET http://localhost:3000/products HTTP/1.1

###

GET http://localhost:3000/products/0.52948s3813686261

###

POST http://localhost:3000/products  HTTP/1.1
content-type: application/json

{
    "title" : "this is a  title",
    "description" : "a brief description of the title",
    "price" : 30
}