GET http://localhost:3000/products HTTP/1.1

###

GET http://localhost:3000/products/656dae09b48c6416e3f7f65c



###

POST http://localhost:3000/products  HTTP/1.1
content-type: application/json

{
    "title" : "product 7",
    "description" : "this is product 76",
    "price" : 30
}

###

PATCH http://localhost:3000/products/656dae09b48c6416e3f7f65c  HTTP/1.1
content-type: application/json

{
    "title" : "brannd new update",
    "description" : "a brief description of the title",
    "price" : 400
}

###
DELETE  http://localhost:3000/products/656328c1aa005abdde5479d5

